[tool.poetry]
name = "flask-aserto"
version = "0.30.3"
description = "Aserto integration for Flask"
readme = "README.md"
authors = ["Aserto, Inc. <pypi@aserto.com>"]
maintainers = ["authereal <authereal@aserto.com>"]
homepage = "https://github.com/aserto-dev/aserto-python/tree/HEAD/packages/flask-aserto"
repository = "https://github.com/aserto-dev/aserto-python/tree/HEAD/packages/flask-aserto"
documentation = "https://github.com/aserto-dev/aserto-python/tree/HEAD/packages/flask-aserto"
license = "Apache-2.0"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Software Development :: Libraries",
  "Typing :: Typed",
]
packages = [
    {include = "flask_aserto", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.8"
Flask = {version = ">=2.0.0,<4.0.0", extras = ["async"]}
Flask-Cors = ">=3.0.0,<5.0.0"
grpcio = "^1.49.0"
protobuf = "^4.21.0"
aserto = "^0.30.1"

[tool.poetry.dev-dependencies]
black = "^23.0"
isort= "^5.9.0"
pyright = "^1.1.0"
pytest = "^7.4.0"

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

